apiVersion: v1
kind: Service
metadata:
  labels:
    app: node1-007
  name: kshitij-service-2
  namespace: default
spec:
  type: NodePort  
  ports:
    - name: http
      protocol: TCP
      port: 8000    
  selector:
    app: my-node1app-007