apiVersion: apps/v1
kind: Deployment
metadata:
  name: gnu-deploy
spec:
  selector:
    matchLabels:
      app: node1-app
  replicas: 1
  template:
    metadata:
      labels:
        app: node1-app
    spec:
      containers:
      - name: nodecontainer
        image: icr.io/ramannamespace/newibmimage:1.0
        ports:
        - containerPort: 3000