apiVersion: portieris.cloud.ibm.com/v1
kind: ClusterImagePolicy
metadata:
  name: ibmcloud-default-cluster-image-policy
spec:
  repositories:
  # Docker hub Container Registry
  - name: "docker.io/*"
    policy:

  # CoreOS Container Registry
  - name: "quay.io/*"
    policy:

  # Google Container Registry
  - name: "gcr.io/*"
    policy:

  # Azure Container Registry
  - name: "*azurecr.io/*"
    policy:


# IBM Container Registry
  - name: "au.icr.io/*"
    policy:
         vulnerability:
          ICCRVA:
            enabled: true
            